name: ${PROJECT_NAME:?}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: "${NETWORK_POOL:?}"

volumes:
  habitat-modules:
    # Ensures the user must have created the bind folder before it is used, default UID and GID are inferred from this mount
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${MODULE_DEPLOY_PATH:?}'

services:

  habitat:
    build:
      context: ./habitat-deploy
    container_name: ${PROJECT_NAME:?}_habitat
    env_file:
      - path: "./.env"
        required: true
      - path: "${MODULE_ENV_FILE:?}"
        required: false
    volumes:
      - habitat-modules:${MODULE_DEPLOY_PATH:?}
      - /var/run/docker.sock:/var/run/docker.sock
